---
title: "Matrici"
author: "Andrea & Ottavia"
date: "`r Sys.Date()`"
output: 
    pdf_document: 
    toc: yes
---

```{r setup, include=FALSE}
#| echo: false
#| eval: true
set.seed(999)
knitr::opts_chunk$set(echo=FALSE, 
                      eval=TRUE, 
                      warning = F, 
                      message = F, 
                      fig.align = "center")

rm(list = ls())

source("Shapes_list-10-11-Ottavia.R")
source("Class and Methods v02.R")
source("Rules_27102022.R")
source("DrawRegPolygon.R")
source("CodiceDistrattoriVero.R")

draws<- function(obj, main = NULL, canvas = TRUE, bg = "white",mar=c(1,1,1,1),xlim=16,by=1.5) {
  library(DescTools)
  if (canvas == TRUE)
  {
    Canvas(xlim=xlim,mar=mar, main = main, bg = bg)
  }
  for(j in 1:length(obj$shape))
  {
    if(obj$visible[[j]]==1)
    {
      if(obj$num[[j]][1]==1){
        if(grepl("line",obj$shade[[j]][1]))
        {
          elements<-decof(obj)
          plotting_lines<-which(obj$visible==1 & grepl("line",unlist(obj$shade)))
          for(ll in 1:length(plotting_lines)){
            line(elements[[plotting_lines[[ll]]]],obj$shade[[j]][1],lwd=3,by=by) #Pejo tacon che sbrego
            
          }
          obj$shade[[j]][1] <- NA
        }
        DrawRegPolygon(x = obj$pos.x[[j]], y = obj$pos.y[[j]], rot = obj$rotation[[j]],
                       radius.x = obj$size.x[[j]], radius.y = obj$size.y[[j]], nv = obj$nv[[j]],
                       lty=obj$lty[[j]],lwd=obj$lwd[[j]],col = obj$shade[[j]])
        
        
      }else{
        
        DrawCircle(x = obj$pos.x[[j]], y = obj$pos.y[[j]],
                   r.out = obj$size.x[[j]],r.in= obj$size.y[[j]], theta.1=obj$theta.1[[j]],
                   theta.2=obj$theta.2[[j]], nv = obj$nv[[j]],
                   lty=obj$lty[[j]],lwd=obj$lwd[[j]],col = obj$shade[[j]])
        
      }
    }
  }
}

lilth<-lily()
s.lilth<-s.lily()
for(i in 1:length(lilth$shape)) {
  lilth$size.x[[i]] <-lilth$size.x[[i]]/2
  lilth$size.y[[i]] <-lilth$size.y[[i]]/2
  lilth$pos.y[[i]] <-lilth$pos.y[[i]]/2
  lilth$pos.x[[i]] <-lilth$pos.x[[i]]/2
  
}

s.lilth$size.x[[1]] <-s.lilth$size.x[[1]]/2
s.lilth$size.y[[1]] <-s.lilth$size.y[[1]]/2
s.lilth$pos.y[[1]] <-s.lilth$pos.y[[1]]/2
s.lilth$pos.x[[1]] <-s.lilth$pos.x[[1]]/2

papillon = bow.tie()
u.papillon = u.bow.tie()


for(i in 1:length(papillon$shape)) {
  papillon$size.x[[i]] <-papillon$size.x[[i]]/2
  papillon$size.y[[i]] <-papillon$size.y[[i]]/2
  papillon$pos.y[[i]] <-papillon$pos.y[[i]]/2
  papillon$pos.x[[i]] <-papillon$pos.x[[i]]/2
  
}

u.papillon$size.x[[1]] <-u.papillon$size.x[[1]]/2
u.papillon$size.y[[1]] <-u.papillon$size.y[[1]]/2
u.papillon$pos.y[[1]] <-u.papillon$pos.y[[1]]/2
u.papillon$pos.x[[1]] <-u.papillon$pos.x[[1]]/2


thepie = pie.4()
u.thepie = u.pie.4()


for(i in 1:length(thepie$shape)) {
  thepie$size.x[[i]] <-thepie$size.x[[i]]/2
  thepie$size.y[[i]] <-thepie$size.y[[i]]/2
  thepie$pos.y[[i]] <-thepie$pos.y[[i]]/2
  thepie$pos.x[[i]] <-thepie$pos.x[[i]]/2
  
}

u.thepie$size.x[[1]] <-u.thepie$size.x[[1]]/2
u.thepie$size.y[[1]] <-u.thepie$size.y[[1]]/2
u.thepie$pos.y[[1]] <-u.thepie$pos.y[[1]]/2
u.thepie$pos.x[[1]] <-u.thepie$pos.x[[1]]/2

biscuit = star()
u.biscuit = u.star()


for(i in 1:length(biscuit$shape)) {
  biscuit$size.x[[i]] <-biscuit$size.x[[i]]/2
  biscuit$size.y[[i]] <-biscuit$size.y[[i]]/2
  biscuit$pos.y[[i]] <-biscuit$pos.y[[i]]/2
  biscuit$pos.x[[i]] <-biscuit$pos.x[[i]]/2
  
}

u.biscuit$size.x[[1]] <-u.biscuit$size.x[[1]]/2
u.biscuit$size.y[[1]] <-u.biscuit$size.y[[1]]/2
u.biscuit$pos.y[[1]] <-u.biscuit$pos.y[[1]]/2
u.biscuit$pos.x[[1]] <-u.biscuit$pos.x[[1]]/2


square4bis <- function() {
  value <-cof(hline(pos.y=-11),vline(pos.x=11),
              hline(pos.y=11),vline(pos.x=-11))
  value$tag <- list("compose4")
  attr(value, "class") <- "field"
  value
}


smallbow.tie.inv <- function(pos.x = 0,pos.y=0,shd=NA) {
  value <-cof(triangle(pos.x = pos.x+5, pos.y = pos.y, rot=pi/3, 
                       s.x = 5, s.y=5,shd = shd), 
              triangle(pos.x = pos.x-5, pos.y = pos.y, rot=-pi, 
                       s.x = 5, s.y=5,shd = shd))
  value$tag <- list("compose2","fill", "rotate")
  attr(value, "class") <- "field"
  value
}


u.smallbow.tie.inv <- function(pos.x = 0,pos.y=0,shd=NA) {
  value <-cof(triangle(pos.x = pos.x+5, pos.y = pos.y, rot=pi/3, 
                       s.x = 5, s.y=5,shd = shd), 
              triangle(pos.x = pos.x-5, pos.y = pos.y, rot=-pi, 
                       s.x = 5, s.y=5,shd = shd), 
              single = T, name = "u.smallbowtie.inv")
  value$tag <- list("compose2","fill", "rotate")
  attr(value, "class") <- "field"
  value
}

bow.tie.inv <- function(pos.x = 0) {
  value <-cof(triangle(pos.x = pos.x+10, pos.y = pos.x, rot=pi/3, 
                       s.x = 10, s.y=10), 
              triangle(pos.x = pos.x-10, pos.y = pos.x, rot=-pi, 
                       s.x = 10, s.y=10))
  value$tag <- list("compose2","fill", "rotate")
  attr(value, "class") <- "field"
  value
}



blu = "deepskyblue3"

giallo = "gold"

rosso = "firebrick"


```

\newpage

# Young 

\newpage

## young001

```{r}

draw(rectangle(s.x=-50,s.y=50,shd=blu,pos.x=+10,pos.y=-7))
draw(diagline(pos.x=-50, s.x = 50, lwd = 3, shd = giallo), canvas = F)
for(i in seq(-50, 50, by = 3.5)) {
  draw(diagline(pos.x = i, s.x=40, lwd = 3), 
       canvas = F)
}


draw(diagline.inv(pos.x=-50, s.x = 50, lwd = 3), canvas = F)
for(i in seq(-50, 50, by = 3.5)) {
  draw(diagline.inv(pos.x = i, s.x=40, lwd = 3), 
       canvas = F)
}


draw(rectangle(s.x=7,s.y=5,shd="white",pos.x=+10,pos.y=-7),
     canvas = FALSE)
```

```{r out.width="80%"}

par(mfrow =c(2, 3), mar = c(0.5, 6, 0.5, 2) + .1, 
          mai=c(.1,.1,.1,.1),oma=c(4,4,0.2,0.2) )

container = rectangle(s.x=7,s.y=5,shd=blu)

draw(container,xlim = 8, main = "correct")
draws(rectangle(s.x=7,s.y=5,shd="line.12.inv"),by=3.5,
     canvas = FALSE)

draws(rectangle(s.x=7,s.y=5,shd="line.12"),by=3.5,
     canvas = FALSE)

draw(container,xlim = 8, main = "ic.scale")
draws(rectangle(s.x=7,s.y=5,shd="line.12"),
     canvas = FALSE)
draws(rectangle(s.x=7,s.y=5,shd="line.12.inv"),
     canvas = FALSE)

draw(container,xlim = 8, main = "difference")

draw(container,xlim = 8, main = "difference")
for (i in seq(-6, 7, by = 3)) {
  for (j in seq(-3, 3, by = 3)) {
    draw(dot(pos.x = i, pos.y = j, size.x = 0.5, size.y = 0.5), canvas = F)
  }
}


draw(container,xlim = 8, main = "ic.flip")
for(i in seq(-7, 7, by = 1)) {
 draw(vline(pos.x = i, s.x=5, lwd = 3), canvas = F)
}

for(i in seq(-5, 5, by = 1)) {
 draw(hline(pos.y = i, s.x=7, lwd = 3), canvas = F)
}

```

## young002 

```{r}
draw(rectangle(s.x=-50,s.y=50,shd=giallo,pos.x=+10,pos.y=-7))
draw(dot(pos.x = -30, pos.y = 15, size.x = 1, size.y = 1, shd = blu), canvas = F)

for (i in seq(-30, 30, by = 4)) {
  for (j in seq(15, -19, by = -4)) {
    draw(dot(pos.x = i, pos.y = j, size.x = 1, size.y = 1, shd = blu), canvas = F)
  }
}

draw(rectangle(s.x=7,s.y=5,shd="white",pos.x=+15,pos.y=-10),
     canvas = FALSE)

```


```{r out.width="80%"}

par(mfrow =c(2, 3), mar = c(0.5, 6, 0.5, 2) + .1, 
          mai=c(.1,.1,.1,.1),oma=c(4,4,0.2,0.2) )

container = rectangle(s.x=7,s.y=5,shd=giallo)

draw(container,xlim = 8, main = "correct")
clip(7,-7,5,-5)
for (i in seq(-21, 25, by = 4)) {
  for (j in seq(12.5, -15, by = -4)) {
     draw(dot(pos.x = i, pos.y = j, size.x = 1, size.y = 1, shd = blu), canvas = F)
  }
}

draw(container,xlim = 8, main = "ic.neg")
clip(7,-7,5,-5)
draw(rectangle(s.x=7,s.y=5,shd=blu,pos.x=0,pos.y=0),
     canvas = FALSE)
for (i in seq(-25, 25, by = 4)) {
  for (j in seq(15, -15, by = -4)) {
        draw(dot(pos.x = i, pos.y = j, size.x = 1, size.y = 1, shd = giallo), canvas = F)
  }
}


draw(container,xlim = 8, main = "difference")


draw(container,xlim = 8, main = "difference1")
clip(7,-7,5,-5)
for (i in seq(-21, 25, by = 4)) {
  for (j in seq(12.5, -15, by = -4)) {
     draw(square(pos.x = i, pos.y = j, s.x = 1, s.y = 1, shd = blu), canvas = F)
  }
}


draw(container,xlim = 8, main = "boh")
draws(rectangle(s.x=7,s.y=5,shd="line.12.inv"),by=3.5,
     canvas = FALSE)
draws(rectangle(s.x=7,s.y=5,shd="line.12"),by=3.5,
     canvas = FALSE)

```


## Young003

```{r}

draw(rectangle(s.x=-50,s.y=50,shd=blu,pos.x=+10,pos.y=-7))
draw(vline(pos.x = -20, s.x = 50, lwd = 3), canvas = F)
draw(vline(pos.x = 20, s.x = 50, lwd = 3, lty = 3), canvas = F)
draw(vline(pos.x = 17, s.x = 50, lwd = 3), canvas = F)
draw(hline(pos.y = 9, s.x = 50, lwd = 3, lty = 1), canvas = F)
draw(hline(pos.y = -9, s.x = 50, lwd = 3, lty = 1), canvas = F)
draw(hline(pos.y = -12, s.x = 50, lwd = 3, lty = 3), canvas = F)


draw(rectangle(s.x=7,s.y=5,shd="white",pos.x=+15,pos.y=-10),
     canvas = FALSE)
```


```{r out.width="80%"}

par(mfrow =c(2, 3), mar = c(0.5, 6, 0.5, 2) + .1, 
          mai=c(.1,.1,.1,.1),oma=c(4,4,0.2,0.2) )

container = rectangle(s.x=7,s.y=5,shd=blu)

draw(container,xlim = 8, main = "correct")

draw(rectangle(s.x=7,s.y=5,shd=NA,pos.x=0,pos.y=0),
     canvas = FALSE)

draw(vline(pos.x = 5, pos.y = -0, 
           s.x  = 5, lwd = 3, lty = 3), canvas = F)
draw(vline(pos.x = 2, pos.y = 0, 
           s.x = 5, lwd = 3), canvas = F)

draw(hline(pos.y = 0, 
           pos.x = 0,  s.x = 7, lwd = 3, lty = 1), canvas = F)
draw(hline(pos.y = -3, pos.x = 0, s.x = 7, lwd = 3, lty = 3), canvas = F)

##primo distrattore
draw(container,xlim = 8, main = "ic")

draw(rectangle(s.x=7,s.y=5,shd=NA,pos.x=0,pos.y=0),
     canvas = FALSE)

draw(vline(pos.x = 5, pos.y = -0, 
           s.x  = 5, lwd = 3, lty = 1), canvas = F)
draw(vline(pos.x = 2, pos.y = 0, 
           s.x = 5, lwd = 3), canvas = F)

draw(hline(pos.y = 0, 
           pos.x = 0,  s.x = 7, lwd = 3, lty = 1), canvas = F)
draw(hline(pos.y = -3, pos.x = 0, s.x = 7, lwd = 3, lty = 1), canvas = F)

##Secondo distrattore

draw(container,xlim = 8, main = "ic")

draw(rectangle(s.x=7,s.y=5,shd=NA,pos.x=0,pos.y=0),
     canvas = FALSE)

draw(vline(pos.x = -5, pos.y = -0, 
           s.x  = 5, lwd = 3, lty = 3), canvas = F)
draw(vline(pos.x = -2, pos.y = 0, 
           s.x = 5, lwd = 3), canvas = F)

draw(hline(pos.y = 0, 
           pos.x = 0,  s.x = 7, lwd = 3, lty = 1), canvas = F)
draw(hline(pos.y = 3, pos.x = 0, s.x = 7, lwd = 3, lty = 3), canvas = F)

##terzo distrattore
draw(container,xlim = 8, main = "wp")
draws(rectangle(s.x=7,s.y=5,shd="line.12.inv"),by=3.5,
     canvas = FALSE)

##quarto
draw(container,xlim = 8, main = "difference")

```


## young004

```{r}

draw(rectangle(s.x=-50,s.y=50,shd=giallo,pos.x=+10,pos.y=-7))
draw(vline(pos.x=-50, s.x = 30, lwd = 1), canvas = F)
for(i in seq(-30, 30, by = 2)) {
  
    draw(vline(pos.x = i, s.x=40, lwd = 1+ abs(i)/2), 
         canvas = F,  bg = "white")
}

draw(rectangle(s.x=7,s.y=5,shd="white",pos.x=+15,pos.y=-10),
     canvas = FALSE)
```



```{r}
par(mfrow =c(2, 3), mar = c(0.5, 6, 0.5, 2) + .1, 
          mai=c(.1,.1,.1,.1),oma=c(4,4,0.2,0.2) )

container = rectangle(s.x=7,s.y=5,shd=giallo)

draw(container,xlim = 8, main = "correct")
clip(7,-7,5,-5)
#for(i in seq(14, 30, by = 1)) {
for(i in seq(6, 22, by = 2)) {
  
    draw(vline(pos.x = i-15, s.x=40, lwd = 1+ abs(i)/2), 
         canvas = F,  bg = "white")
}


draw(container,xlim = 8, "wp")
clip(7,-7,5,-5)
for(i in seq(14, 30, by = 1)) {
  
    draw(vline(pos.x = i-22, s.x=40, lwd = 5), 
         canvas = F,  bg = "white")
}

draw(container,xlim = 8, main = "difference")

draw(container,xlim = 8, main = "boh")
draws(rectangle(s.x=7,s.y=5,shd="line.12.inv"),by=3.5,
     canvas = FALSE)

draw(container,xlim = 8, "wp")
draws(rectangle(s.x=7,s.y=5,shd="line.12.inv"),by=3.5,
     canvas = FALSE)
draws(rectangle(s.x=7,s.y=5,shd="line.12"),by=3.5,
     canvas = FALSE)
```

## Young005

```{r}

```


## Young006

```{r}
young006 = apply(Raven(
    st1 = cof( 
              rectangle(s.x = 25, s.y = 15, pos.y = -1, shd = blu), 
              triangle(pos.y = 0, s.x = 12, s.y = 12, shd = giallo)), 
    vrule = "reflection", 
    hrule = "identity"
))
draw(young006, n.cell = 4, hide = F)
```


```{r out.width="80%"}
dist_young006 = responses(young006,mat.type = 4)
draw.dist(dist_young006, n.resp = 11, main = T)
```


## Young007

```{r}
young007a = apply(Raven(
  st1 = pacman(size.x = 7, shd = rosso), 
  hrule = "reflection", 
  vrule = "reflection"
))

young007b = apply(Raven(
  st1 = pentagon(shd = giallo), 
  hrule = "identity", 
  vrule = "identity"
))


young007 = com(young007b, young007a)
draw(young007, n.cell = 4)

```


```{r out.width="80%"}
dist_young007 = responses(young007,mat.type = 4)
draw.dist(dist_young007, n.resp = 11, main = T)
```


## Young008

```{r}

young008a = apply(Raven(
  st1 = dot(), 
  vrule = "fill"
))

young008b = apply(Raven(
  st1 = pacman(shd = rosso), 
  "reflection"
))

young008 = com(young008b, young008a)

draw(young008, n.cell = 4)
```

```{r out.width="80%"}
dist_young008 = responses(young008, mat.type = 4)

draw.dist(dist_young008)

```


## Young009

```{r}
young009a = apply(Raven(
  st1 = cof(s.lilth, 
            pacman(size.x = 5), ellipse()),
  vrule = "diff_shapes"
  
))

young009b = apply(Raven(
  st1 = cof(e.hexagon(shd = blu), 
            circle(shd = giallo,s.x = 15, s.y = 15), 
            triangle()), 
  vrule = "diff_shapes"
))

young009 = com(young009b, young009a)

draw(young009, n.cell = 4)

```

```{r out.width="80%"}

dist_young009 = responses(young009, mat.type = 4)

draw.dist(dist_young009)

```

## young010 

```{r}

young010a = apply(Raven(
  st1 = cof(u.pie.2(size.x = 5, shd = blu),
           u.pie.4(size.x = 5, shd = rosso), ellipse()),
  vrule = "diff_shapes"

))

young010b = apply(Raven(
  st1 = cof(e.hexagon(shd = giallo, s.x = 13, s.y = 13),
            triangle(shd = giallo, s.x = 15, s.y = 15),
            circle()),
  hrule = "diff_shapes"
))

young010 = com(young010b, young010a)

draw(young010, n.cell = 4)
```

## young011

```{r}


young011 = apply(Raven(
  st1 = cof(e.hexagon(shd = giallo, s.x = 13, s.y = 13),
            triangle(shd = giallo, s.x = 15, s.y = 15),
            circle()),
  vrule = c( "reflection", "diff_shapes")
))


draw(young011, n.cell = 4)
```

```{r out.width="80%"}

```


## Young012 


```{r}

young012a = apply(Raven(
  st1 = cof(pentagon(shd = giallo, s.x = 13, s.y = 13),
            triangle(shd = giallo, s.x = 15, s.y = 15),
            circle()),
  vrule = "diff_shapes",
  hrule = "reflection"
))

young012b = apply(Raven(
  st1 = dot(size.x = 2, size.y = 1, shd = rosso)
))

young012 = com(young012a, young012b)
draw(young012, n.cell = 4)
```


## young026 

```{r}
set.seed(999)
young026a = apply(
  Raven(
    st1 = cof(square(shd = giallo), u.bow.tie(shd = giallo), triangle(rot = pi/2, shd = giallo)), 
    vrule = c("diff_shapes"), 
    hrule = "identity"
  )
)

young026b = apply(Raven(
  st1 = cof(dot(shd = blu))
))

young026 = com(young026a, young026b)
draw(young026, n.cell = 9)


```

```{r out.width="80%"}

dist_young026 = responses(young026)
draw.dist(dist_young026, n.resp = 11, main = T)

```


## young027 

```{r}
young027a= apply(
  Raven(
    st1 = cof(pentagon(shd = rosso), triangle(shd = rosso), square(shd = rosso)), 
    hrule = c("diff_shapes"), 
    vrule = "identity"
  )
)

young027b = apply(Raven(
  st1 = cof(dot(shd = giallo, size.x = 7)), 
  hrule = "size"
))


young027 = com(young027a, young027b)

draw(young027, hide = F)
```

```{r out.width="80%"}
dist_young027 = responses(young027)
draw.dist(dist_young027, n.resp = 11, main = T)
```


## young028

```{r}
young028a = apply(Raven(
  st1 = square(shd = giallo)
))

young028b = apply(Raven(
  st1 = pacman(), 
  hrule = "fill"
))

young028 = com(young028a, young028b)
draw(young028)
```


```{r out.width="80%"}
dist_young028 = responses(young028)

draw.dist(dist_young028)

```

## young029 

```{r}
young029a = apply(Raven(
  st1=rectangle(shd = blu, s.x = 20, s.y = 15)
))



young029b= apply(
  Raven(
    st1 = cof(pentagon(shd = "black", s.x = 12, s.y = 12), u.star(), square(shd = "black")), 
    vrule = c("diff_shapes", "size"), 
    hrule = "identity"
  )
)

young029 = com(young029a, young029b)

draw(young029)
```


```{r out.width="80%"}
dist_young029 = responses(young029)

draw.dist(dist_young029)
```


## young030 

```{r}
young030a = apply(Raven(
  st1 = cof(square(s.x = 18, s.y = 18), e.hexagon(), 
            pentagon()), 
  hrule = "diff_shapes"
))

young030b = apply(Raven(
  st1 = pacman(shd = rosso, size.x = 8), 
  vrule = "size"
  
))


young030 = com(young030a, young030b)

draw(young030)

```


```{r out.width="80%"}
dist_young030 = responses(young030)


draw.dist(dist_young030)

```


## young031

```{r}
young031a = apply(Raven(
  st1=rectangle(shd = giallo, s.x = 20, s.y = 15)
))

young031b = apply(Raven(
  st1 = cof(u.smallbow.tie.inv(shd = blu), size(u.star(), 2), u.pie.4( 
                                                    shd = rosso)), 
  vrule  = "diff_shapes"
))

young031 = com(young031a, young031b)

draw(young031)

```


```{r}
dist_young031 = responses(young031)

draw.dist(dist_young031)

```

## young032

```{r}
young032a = apply(Raven(
  st1=cof(square(shd = giallo), 
          square(shd = blu), 
          square(shd = rosso)), 
  hrule = "diff_shapes"
))

young032b = apply(Raven(
  st1 = cof(u.smallbow.tie.inv(shd = "black"), size(u.star(), 2), 
            size(pacman(shd = "black"), 2)), 
  vrule  = "diff_shapes"
))

young032 = com(young032a, young032b)

draw(young032)
```

```{r out.width="80%"}

dist_young032 = responses(young032)

draw.dist(dist_young032)
```

## young033

```{r}
young033 = apply(
  Raven(
    st1 = cof(square(shd = "black"), u.star(), triangle(rot = pi/2, shd = "black")), 
    vrule = c("diff_shapes", "size")
  )
)
draw(young033, n.cell = 9, hide = T)
```

```{r out.width="80%"}

dist_young033 = responses(young033)


draw.dist(dist_young033)
```


## Young034


```{r}
young034a = apply(Raven(
  st1 = cof(u.star(), pentagon(shd = "black"), e.hexagon(shd = "black")), 
  vrule = "diff_shapes"
))

young034b = apply(
  Raven(
    st1 = dot(shd = "white", size.x = 10), 
    hrule = c("size")
  )
)

young034 = com(young034a, young034b)


draw(young034, n.cell = 9, hide = T)
```

```{r out.width="80%"}

dist_young034 = responses(young034)


draw.dist(dist_young034)
```


## Young035 


```{r}
young035a = apply(Raven(
  st1 = square()
))

young035b = apply(Raven(
  st1 = cof(u.smallbow.tie.inv(), u.pie.2(), pacman()), 
  vrule = c("diff_shapes", "fill")
))

young035 = com(young035a, young035b)


draw(young035)
```


```{r}
dist_young035 = responses(young035)

draw.dist(dist_young035)
```


## Young036

```{r}
a_3a = apply(
  Raven(
    st1 = cof(circle(s.x = 17, s.y = 17), 
              pentagon(s.x = 16, s.y = 16), 
              e.hexagon(s.x = 17, s.y = 17)), 
    vrule = c("diff_shapes"), 
    hrule = "diff_shapes"
  )
)

a_3b = apply(
  Raven(
    st1 = pacman()
  )
)


a_3c = apply(
  Raven(
    st1 = circle(s.x = 2, s.y = 2), 
    vrule = c("fill"), 
    hrule = "fill"
  )
)

young036 = com(a_3a, a_3b, a_3c)
draw(young036, hide = F)
```

```{r out.width="80%"}
dist_young036 = responses(young036)

draw.dist(dist_young036)

```

